source:
  source_data_type: "database"
  db_type: "postgres"
  host: "localhost"
  database_name: "mydb"
  username: "user"
  password: "password"
  port: 5432
  query: "SELECT * FROM mytable WHERE updated_at > :last_updated_at"
  batch_size: 1000 #[Optional] Default is 1000
  chunk_size: 1000 #[Optional] Default is 1000
  chunk_overlap: 0 #[Optional] Default is 0

embedding:
  embedding_model: "Cohere"
  api_key: "my-cohere-key"
  model_name: "embed-english-v3.0"

target:
 target_database: "Weaviate"
 weaviate_url: "https://your-cluster-details.weaviate.cloud" #replace with your Weaviate cluster url
 weaviate_api_key: "your-cluster-api-key" #replace with your Weaviate API keys
 class_name: "collection-name" #replace with an existing or new collection name

embed_columns:
  - "column1"
  - "column2"
  - "column3"